include: package:flutter_lints/flutter.yaml

linter:
  rules:
    prefer_const_constructors: true
    prefer_const_literals_to_create_immutables: true
    avoid_print: true
    prefer_final_fields: true
    prefer_final_locals: true
    always_declare_return_types: true
    avoid_dynamic_calls: true
    directives_ordering: true
    unnecessary_late: true
    use_full_hex_values_for_flutter_colors: true
