name: income_expense_tracker
description: A clean architecture Flutter app to track income and expenses with BLoC, SQLite, and Material 3 UI.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # State management
  flutter_bloc: ^8.1.4
  equatable: ^2.0.5

  # Database
  sqflite: ^2.3.3
  path_provider: ^2.1.3
  path: ^1.9.0

  # Charts
  fl_chart: ^0.69.0

  # Utils
  intl: 0.20.2
  uuid: ^4.4.0
  google_fonts: ^6.2.1
  json_annotation: ^4.9.0
  clipboard: ^0.1.3
  flutter_screenutil: ^5.9.3
  animated_notch_bottom_bar: ^1.0.3
  phosphor_flutter: ^2.0.1
  flutter_launcher_icons: ^0.14.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  bloc_test: ^9.1.7
  build_runner: ^2.4.11
  json_serializable: ^6.8.0
  flutter_lints: ^3.0.2

flutter_icons:
  android: true
  ios: true
  image_path_android: "assets/images/main_logo.png"
  image_path_ios: "assets/images/main_logo.png"

flutter:
  uses-material-design: true

  assets:
    - assets/images/
